### ISSUE TITLE
Make an interface for storing data

### ISSUE THREAD

**Issue by A5rocks** [A5rocks/code-jam-11#3]
We need to store data:
 - characters per second per user
 - whether a channel has this enabled
 - currency

We should store these in memory (using a global dictionary) for now, but in a separate module so it's easy to drop in a database later.

**Comment by A5rocks** [comment]
Actually making this a class rather than global functions would probably work better

**Comment by LuckElixir** [comment]
I've set up a database module with a class that holds user data and channel data. I'll most likely push documentation for these soon after
