### ISSUE TITLE
Figure out how to test this

### ISSUE THREAD

**Issue by A5rocks** [A5rocks/code-jam-11#6]
We'll probably get a better ranking if we have a way to test our code. I'm not sure how we can yet, this issue is for brainstorming.

**Comment by aceeedev** [comment]
Some possible resources

- https://github.com/Rapptz/discord.py/issues/197
- https://pypi.org/project/dpytest/

**Comment by A5rocks** [comment]
I don't think we'll need to use any sort of complex thing cause we're in the enviable position of a purely command-response thing (other than the send command).

But yeah potentially useful
